thrift: drop stdcxx namespace
since thrift has dropped support for stdcxx.h that makes jaeger
incompatible with latest thrift and hence jaeger failure:

/home/ideepika/ceph-primary/ceph/src/jaegertracing/jaeger-client-cpp/src/jaegertracing/thrift-gen/agent_types.h:18:10: fatal error: thrift/stdcxx.h: No such file or directory
   18 | #include <thrift/stdcxx.h>
      |          ^~~~~~~~~~~~~~~~~
this change will make jaeger compatible with latest thrift.

see: https://github.com/apache/thrift/pull/1677

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>