[thrift] drop stdcxx namespace (#239)
* thrift: drop stdcxx namespace

since thrift has dropped support for stdcxx.h that makes jaeger
incompatible with latest thrift and hence jaeger failure:

/home/ideepika/ceph-primary/ceph/src/jaegertracing/jaeger-client-cpp/src/jaegertracing/thrift-gen/agent_types.h:18:10: fatal error: thrift/stdcxx.h: No such file or directory
   18 | #include <thrift/stdcxx.h>
      |          ^~~~~~~~~~~~~~~~~
this change will make jaeger compatible with latest thrift.

see: https://github.com/apache/thrift/pull/1677

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

* thrift: fix warning due to difference in naming.

fixes warning:

CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (THRIFT)
  does not match the name of the calling package (thrift).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Findthrift.cmake:92 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:63 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

Co-authored-by: Yuri Shkuro <yurishkuro@users.noreply.github.com>